### ISSUE TITLE
Create a Docs SIG

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/steering#4]
This issue mirrors https://github.com/jenkins-x/jx-docs/issues/2675

## Goals
* Discuss documentation and docs issues for jenkins-x.io
* Review and coordinate documentation for new Jenkins X features
* Suggest improvements to user onboarding through better documentation on  jenkins-x.io
* Help community contributors get involved in Jenkins X documentation
* Content for the official Jenkins X blog
* Organize and revise technical content to improve UX and technical accuracy and keep content up to date, based on:

     * user-reported issues
     * content audits performed by SIG members

## Leadership

The Chair of the SIG, with agreement from Members, will run operations and processes governing the SIG. He/she will also establish and decommission subprojects.

Proposed Chair: @ethangj 

Proposed Working Groups / Subprojects and respective leaders:
* Content and Writing Quality: @jha-cloudbees 
* Structure of docs site: @sharepointoscar 
* 中文 translation: @LinuxSuRen 
* Spanish translation: @mmorejon 
* Season of Docs: @MarckK 

### Members
Membership to the SIG is open and we welcome new members to join!

## Contact
- [Open Community Issues/PRs](https://github.com/jenkins-x/jx-docs/issues)

## Meetings
* The Docs SIG meets every Monday at 16:30 UTC (*See your timezone [here](https://time.is/1630_in_UTC)*)
* Meetings will be recorded and made available on the [Jenkins X YouTube Channel](https://www.youtube.com/channel/UCN2kblPjXKMcjjVYmwvquvg)

**Comment by LinuxSuRen** [comment]
Do we have a meeting calendar?

**Comment by MarckK** [comment]
@LinuxSuRen is 16:30 UTC very late at night for you? 
Our members are based globally, including CA and the EU; bridging all the time zones is very difficult. It would be great to have you in the meetings. 

Would meeting at around 14:00 UTC on a weekday work for you?

We do have a [Jenkins X events calendar](https://jenkins-x.io/community/), but have not added the Docs SIG to the calendar yet, as we need to find an agreement on the best time.

**Comment by MarckK** [comment]
Different working groups will likely have additional meetings. For example, for Season of Docs, we will almost certainly have office hours or a meeting time arranged with our interested technical writers. Similarly, the Chinese localisation working group can set up a more convenient time to meet to work specifically on that topic.

**Comment by LinuxSuRen** [comment]
@MarckK 14:00 UTC be better for me. You can send me a meeting link. Thanks.

**Comment by MarckK** [comment]
@LinuxSuRen Further discussion needs to happen to work out the final meeting time for the Docs SIG, as there are a number of people involved.

What we'll do is have our initial meeting at 16:30 UTC next Monday, 18 May. See, [Jenkins X calendar](https://jenkins-x.io/community/). It will be an action item for the SIG to discuss changing the meeting time and we can create an issue to discuss meeting times on the Docs SIG repo, which will get set up over the next week.

**Comment by MarckK** [comment]
[Docs SIG repo](https://github.com/jenkins-x/jx-community/tree/master/sig-docs) created 🎉

**Comment by MarckK** [comment]
Closing as Docs SIG is happening. :)
